/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FSwapPool } from "./FSwapPool";
export type { FToken } from "./FToken";
export type { GCoin } from "./GCoin";
